---
- name: Analizar Drupal
  hosts: webservers
  gather_facts: false
  tasks:
  - name: Verificar versión de Drupal
    shell: drush status | grep "Drupal version"
    register: drupal_version
  - name: Verificar plugins desactualizados
    shell: drush pml --no-core --status=insecure | awk '{print $1}'
    register: inactive_plugins
  - name: Verificar configuración de seguridad
    shell: drush eval 'print_r(drupal_security_review());'
    register: security_check
  - name: Verificar cumplimiento de la RGPD
    shell: drush eval 'print_r(drupal_gdpr_compliance());'
    register: gdpr_check
  - name: Verificar rendimiento
    shell: drush eval 'print_r(drupal_performance_check());'
    register: performance_check
  - name: Mejorar configuración de seguridad
    shell: drush eval 'drupal_security_review_fix();'
    when: "security_check.stdout | trim != 'Success: Drupal is secure'"
  - name: Mejorar cumplimiento de la RGPD
    shell: drush eval 'drupal_gdpr_compliance_fix();'
    when: "gdpr_check.stdout | trim != 'Success: Drupal is RGPD compliant'"
  - name: Mejorar rendimiento
    shell: drush eval 'drupal_performance_check_fix();'
    when: "performance_check.stdout | trim != 'Success: Drupal is optimized for performance'"
  - name: Mostrar resultados
    debug:
      var:
        drupal_version: "{{ drupal_version.stdout }}"
        inactive_plugins: "{{ inactive_plugins.stdout_lines }}"
        security_check: "{{ security_check.stdout }}"
        gdpr_check: "{{ gdpr_check.stdout }}"
        performance_check: "{{ performance_check.stdout }}"
